# Generated by Django 3.2.5 on 2022-07-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='booze',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='food',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='kakaourl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
